#!/usr/bin/env python3
"""
Pseudobulk Differential Expression Pipeline

This script generates pseudobulk samples from single-cell data and prepares
for DESeq2 analysis. Use this for multi-replicate studies.

Usage:
    python pseudobulk_pipeline.py input.h5ad --sample-col donor_id --groupby cell_type --condition condition
"""

import argparse
import os
import scanpy as sc
import pandas as pd
import numpy as np
from scipy import sparse


def create_pseudobulk(
    adata,
    sample_col: str,
    groupby: str,
    layer: str = None,
    min_cells: int = 10,
    min_counts: int = 10,
):
    """
    Create pseudobulk samples by aggregating cells.
    
    Parameters
    ----------
    adata : AnnData
        Input AnnData object
    sample_col : str
        Column identifying biological samples (donors)
    groupby : str
        Column for grouping (cell type)
    layer : str
        Layer containing raw counts
    min_cells : int
        Minimum cells per pseudobulk sample
    min_counts : int
        Minimum counts per gene
        
    Returns
    -------
    counts_df : pd.DataFrame
        Pseudobulk counts (genes x samples)
    metadata_df : pd.DataFrame
        Sample metadata
    """
    
    # Get counts matrix
    if layer is not None:
        X = adata.layers[layer]
    elif adata.raw is not None:
        X = adata.raw.X
    else:
        X = adata.X
    
    if sparse.issparse(X):
        X = X.toarray()
    
    # Create sample identifiers
    sample_ids = [
        f"{sample}_{group}" 
        for sample, group in zip(adata.obs[sample_col], adata.obs[groupby])
    ]
    adata.obs["pseudobulk_id"] = sample_ids
    
    # Aggregate by pseudobulk sample
    print(f"Aggregating cells into pseudobulk samples...")
    
    unique_samples = adata.obs["pseudobulk_id"].unique()
    pseudobulk_counts = []
    sample_metadata = []
    
    for ps_id in unique_samples:
        mask = adata.obs["pseudobulk_id"] == ps_id
        n_cells = mask.sum()
        
        if n_cells < min_cells:
            print(f"  Skipping {ps_id}: only {n_cells} cells")
            continue
        
        # Sum counts
        counts_sum = X[mask.values, :].sum(axis=0)
        if hasattr(counts_sum, 'A1'):
            counts_sum = counts_sum.A1
        
        pseudobulk_counts.append(counts_sum)
        
        # Get metadata (first cell's values)
        meta = {
            "pseudobulk_id": ps_id,
            sample_col: adata.obs.loc[mask, sample_col].iloc[0],
            groupby: adata.obs.loc[mask, groupby].iloc[0],
            "n_cells": n_cells
        }
        
        # Add condition if available
        if "condition" in adata.obs.columns:
            meta["condition"] = adata.obs.loc[mask, "condition"].iloc[0]
        
        sample_metadata.append(meta)
    
    # Create DataFrames
    counts_df = pd.DataFrame(
        pseudobulk_counts,
        index=[m["pseudobulk_id"] for m in sample_metadata],
        columns=adata.var_names
    ).T  # genes x samples
    
    metadata_df = pd.DataFrame(sample_metadata).set_index("pseudobulk_id")
    
    # Filter low-count genes
    gene_counts = (counts_df >= min_counts).sum(axis=1)
    keep_genes = gene_counts >= 2  # At least 2 samples with min_counts
    counts_df = counts_df[keep_genes]
    print(f"Kept {len(counts_df)} genes after filtering")
    
    print(f"\nCreated {len(counts_df.columns)} pseudobulk samples")
    print(f"  Samples: {metadata_df[sample_col].nunique()}")
    print(f"  Groups: {metadata_df[groupby].nunique()}")
    
    return counts_df, metadata_df


def generate_deseq2_script(output_dir: str, design: str = "~ condition"):
    """Generate R script for DESeq2 analysis."""
    
    r_script = '''#!/usr/bin/env Rscript
# DESeq2 Analysis Script
# Generated by pseudobulk_pipeline.py

library(DESeq2)
library(tidyverse)

# Load data
counts <- read.csv("pseudobulk_counts.csv", row.names = 1)
metadata <- read.csv("pseudobulk_metadata.csv", row.names = 1)

# Ensure column names match
counts <- counts[, rownames(metadata)]

# Create DESeq2 object
dds <- DESeqDataSetFromMatrix(
    countData = counts,
    colData = metadata,
    design = formula("{design}")
)

# Filter low-count genes
keep <- rowSums(counts(dds) >= 10) >= 3
dds <- dds[keep, ]

# Run DESeq2
cat("Running DESeq2...\\n")
dds <- DESeq(dds)

# Get results
cat("Getting results...\\n")
res <- results(dds, alpha = 0.05)

# Apply LFC shrinkage
resLFC <- lfcShrink(dds, coef = ncol(dds), type = "apeglm")

# Save results
results_df <- as.data.frame(resLFC) %>%
    rownames_to_column("gene") %>%
    arrange(padj)

write.csv(results_df, "deseq2_results.csv", row.names = FALSE)

# Summary
cat("\\n=== DESeq2 Results Summary ===\\n")
cat(sprintf("Total genes tested: %d\\n", nrow(res)))
cat(sprintf("Significant (padj < 0.05, |log2FC| > 1): %d\\n", 
    sum(res$padj < 0.05 & abs(res$log2FoldChange) > 1, na.rm = TRUE)))

# Print top genes
cat("\\nTop 10 DE genes:\\n")
print(head(results_df, 10))
'''
    
    script_path = os.path.join(output_dir, "run_deseq2.R")
    with open(script_path, 'w') as f:
        f.write(r_script.format(design=design))
    
    return script_path


def main():
    parser = argparse.ArgumentParser(
        description="Generate pseudobulk for DESeq2 analysis"
    )
    parser.add_argument("input", help="Input AnnData file (.h5ad)")
    parser.add_argument("--sample-col", required=True, help="Sample/donor column")
    parser.add_argument("--groupby", required=True, help="Cell type column")
    parser.add_argument("--condition", default="condition", help="Condition column")
    parser.add_argument("--output", default="pseudobulk", help="Output directory")
    parser.add_argument("--min-cells", type=int, default=10, help="Min cells per sample")
    parser.add_argument("--layer", default=None, help="Count layer")
    parser.add_argument("--design", default="~ condition", help="DESeq2 design formula")
    
    args = parser.parse_args()
    
    # Load data
    print(f"Loading data from {args.input}")
    adata = sc.read_h5ad(args.input)
    
    # Check required columns
    for col in [args.sample_col, args.groupby]:
        if col not in adata.obs.columns:
            raise ValueError(f"Column '{col}' not found in adata.obs")
    
    # Create output directory
    os.makedirs(args.output, exist_ok=True)
    
    # Generate pseudobulk
    counts_df, metadata_df = create_pseudobulk(
        adata,
        sample_col=args.sample_col,
        groupby=args.groupby,
        layer=args.layer,
        min_cells=args.min_cells
    )
    
    # Save pseudobulk data
    counts_path = os.path.join(args.output, "pseudobulk_counts.csv")
    metadata_path = os.path.join(args.output, "pseudobulk_metadata.csv")
    
    counts_df.to_csv(counts_path)
    metadata_df.to_csv(metadata_path)
    
    print(f"\nSaved pseudobulk counts to {counts_path}")
    print(f"Saved metadata to {metadata_path}")
    
    # Generate DESeq2 script
    script_path = generate_deseq2_script(args.output, args.design)
    print(f"Generated DESeq2 script: {script_path}")
    
    # Print next steps
    print("\n=== Next Steps ===")
    print("1. Review pseudobulk_metadata.csv to verify sample assignments")
    print("2. Edit run_deseq2.R to adjust design formula if needed")
    print("3. Run: Rscript run_deseq2.R")
    
    # Print sample summary
    print("\n=== Pseudobulk Summary ===")
    print(metadata_df.groupby([args.sample_col, args.groupby]).size().unstack(fill_value=0))


if __name__ == "__main__":
    main()
